# Dependabot configuration for SlotWise microservices
# Enhanced with dependency grouping to reduce conflicts and maintenance overhead
version: 2
updates:
  # Root workspace dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "michaelfperla"
    assignees:
      - "michaelfperla"
    groups:
      root-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(root)"
      include: "scope"

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "michaelfperla"
    assignees:
      - "michaelfperla"
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "next*"
          - "@next/*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      ui-libraries:
        patterns:
          - "@radix-ui/*"
          - "tailwind*"
          - "@tailwindcss/*"
          - "lucide-react"
          - "clsx"
        update-types:
          - "minor"
          - "patch"
      state-management:
        patterns:
          - "@tanstack/*"
          - "zustand"
          - "axios"
          - "zod"
        update-types:
          - "minor"
          - "patch"
      frontend-dev-tools:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "typescript"
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(frontend)"
      include: "scope"

  # Shared types dependencies
  - package-ecosystem: "npm"
    directory: "/shared/types"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "michaelfperla"
    assignees:
      - "michaelfperla"
    groups:
      shared-types:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(shared/types)"
      include: "scope"

  # Shared utils dependencies
  - package-ecosystem: "npm"
    directory: "/shared/utils"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "michaelfperla"
    assignees:
      - "michaelfperla"
    groups:
      shared-utils:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(shared/utils)"
      include: "scope"

  # Business service dependencies
  - package-ecosystem: "npm"
    directory: "/services/business-service"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "michaelfperla"
    assignees:
      - "michaelfperla"
    groups:
      fastify-ecosystem:
        patterns:
          - "fastify*"
          - "@fastify/*"
        update-types:
          - "minor"
          - "patch"
      database-tools:
        patterns:
          - "prisma"
          - "@prisma/*"
        update-types:
          - "minor"
          - "patch"
      auth-security:
        patterns:
          - "bcryptjs"
          - "jsonwebtoken"
          - "@types/bcryptjs"
          - "@types/jsonwebtoken"
        update-types:
          - "minor"
          - "patch"
      messaging-caching:
        patterns:
          - "nats"
          - "ioredis"
        update-types:
          - "minor"
          - "patch"
      utilities:
        patterns:
          - "zod"
          - "nanoid"
          - "date-fns"
          - "dotenv"
        update-types:
          - "minor"
          - "patch"
      logging:
        patterns:
          - "pino*"
        update-types:
          - "minor"
          - "patch"
      business-dev-tools:
        patterns:
          - "typescript"
          - "tsx"
          - "@types/*"
          - "jest"
          - "ts-jest"
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
          - "rimraf"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "fastify"
        update-types: ["version-update:semver-major"]
      - dependency-name: "prisma"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(business-service)"
      include: "scope"

  # Notification service dependencies
  - package-ecosystem: "npm"
    directory: "/services/notification-service"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "michaelfperla"
    assignees:
      - "michaelfperla"
    groups:
      fastify-ecosystem:
        patterns:
          - "fastify*"
          - "@fastify/*"
        update-types:
          - "minor"
          - "patch"
      notification-providers:
        patterns:
          - "@sendgrid/*"
          - "twilio"
        update-types:
          - "minor"
          - "patch"
      template-processing:
        patterns:
          - "handlebars"
          - "mjml"
          - "@types/handlebars"
        update-types:
          - "minor"
          - "patch"
      queue-processing:
        patterns:
          - "bull"
          - "@types/bull"
        update-types:
          - "minor"
          - "patch"
      database-messaging:
        patterns:
          - "prisma"
          - "@prisma/*"
          - "nats"
          - "ioredis"
        update-types:
          - "minor"
          - "patch"
      utilities:
        patterns:
          - "zod"
          - "nanoid"
          - "date-fns"
          - "dotenv"
        update-types:
          - "minor"
          - "patch"
      logging:
        patterns:
          - "pino*"
        update-types:
          - "minor"
          - "patch"
      notification-dev-tools:
        patterns:
          - "typescript"
          - "tsx"
          - "@types/*"
          - "jest"
          - "ts-jest"
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
          - "rimraf"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(notification-service)"
      include: "scope"

  # Auth service Go dependencies
  - package-ecosystem: "gomod"
    directory: "/services/auth-service"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "michaelfperla"
    assignees:
      - "michaelfperla"
    groups:
      web-framework:
        patterns:
          - "github.com/gin-gonic/*"
        update-types:
          - "minor"
          - "patch"
      auth-security:
        patterns:
          - "github.com/golang-jwt/*"
          - "golang.org/x/crypto"
        update-types:
          - "minor"
          - "patch"
      database-orm:
        patterns:
          - "gorm.io/*"
        update-types:
          - "minor"
          - "patch"
      messaging-caching:
        patterns:
          - "github.com/nats-io/*"
          - "github.com/redis/*"
        update-types:
          - "minor"
          - "patch"
      configuration:
        patterns:
          - "github.com/spf13/*"
        update-types:
          - "minor"
          - "patch"
      utilities:
        patterns:
          - "github.com/google/uuid"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(auth-service)"
      include: "scope"

  # Scheduling service Go dependencies
  - package-ecosystem: "gomod"
    directory: "/services/scheduling-service"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "michaelfperla"
    assignees:
      - "michaelfperla"
    groups:
      web-framework:
        patterns:
          - "github.com/gin-gonic/*"
        update-types:
          - "minor"
          - "patch"
      database-orm:
        patterns:
          - "gorm.io/*"
          - "github.com/lib/pq"
        update-types:
          - "minor"
          - "patch"
      scheduling:
        patterns:
          - "github.com/robfig/cron/*"
        update-types:
          - "minor"
          - "patch"
      messaging-caching:
        patterns:
          - "github.com/nats-io/*"
          - "github.com/redis/*"
        update-types:
          - "minor"
          - "patch"
      configuration:
        patterns:
          - "github.com/spf13/*"
        update-types:
          - "minor"
          - "patch"
      utilities:
        patterns:
          - "github.com/google/uuid"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(scheduling-service)"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/infrastructure"
    schedule:
      interval: "monthly"
      day: "first-tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "michaelfperla"
    assignees:
      - "michaelfperla"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "first-monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "michaelfperla"
    assignees:
      - "michaelfperla"
    commit-message:
      prefix: "chore(github-actions)"
      include: "scope"
