environment: development
port: 8001
log_level: info

database:
  host: localhost
  port: 5432
  user: slotwise
  password: slotwise_dev_password
  name: slotwise
  ssl_mode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

nats:
  url: nats://localhost:4222
  subject: slotwise.auth

jwt:
  secret: your-super-secret-jwt-key-change-in-production
  access_token_ttl: 15m
  refresh_token_ttl: 168h
  issuer: slotwise-auth-service

email:
  provider: sendgrid
  api_key: ${SENDGRID_API_KEY}
  from: noreply@slotwise.com

rate_limit:
  requests_per_minute: 1000
  burst_size: 100
  cleanup_interval: 1m
  auth_requests_per_minute: 100  # More lenient for auth endpoints in dev
